# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c7ce287473118fabac56b16b54406410cd3ec5471701156733be0628ed812a0889f78b13a48091139ed15ecbceac6c0ecb00e0e1798bc26f0df32f67779ec74

test:
  secret_key_base: 586700721871fe34822eca9ad93e350fdad36cc9b28965bc0306ca9f57dfc115fd1d62ef6f428315cc5dc7c7a0fd567d9ee95470a7f28e8cc4a6ea6c1dea8fb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
